products:
  template: 'Products/List.twig'
  pageTitle: 'Products'
  public: true
  dataProcessing:
    products: getProductsAll

products/{id}:
  template: 'Products/Detail.twig'
  pageTitle: 'Product details'
  public: true
  dataProcessing:
    product: getProduct